//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreLab1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class SettingsAdmin : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsAdmin defaultInstance = ((SettingsAdmin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsAdmin())));
        
        public static SettingsAdmin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Admin_CheckSquare {
            get {
                return ((bool)(this["Admin_CheckSquare"]));
            }
            set {
                this["Admin_CheckSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_CheckTriangle {
            get {
                return ((bool)(this["Admin_CheckTriangle"]));
            }
            set {
                this["Admin_CheckTriangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_CheckRound {
            get {
                return ((bool)(this["Admin_CheckRound"]));
            }
            set {
                this["Admin_CheckRound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_rBtnEasy {
            get {
                return ((bool)(this["Admin_rBtnEasy"]));
            }
            set {
                this["Admin_rBtnEasy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Admin_rBtnNormal {
            get {
                return ((bool)(this["Admin_rBtnNormal"]));
            }
            set {
                this["Admin_rBtnNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_rBtnHard {
            get {
                return ((bool)(this["Admin_rBtnHard"]));
            }
            set {
                this["Admin_rBtnHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_rBtnCustom {
            get {
                return ((bool)(this["Admin_rBtnCustom"]));
            }
            set {
                this["Admin_rBtnCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Admin_diffCustomNum1 {
            get {
                return ((int)(this["Admin_diffCustomNum1"]));
            }
            set {
                this["Admin_diffCustomNum1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Admin_diffCustomNum2 {
            get {
                return ((int)(this["Admin_diffCustomNum2"]));
            }
            set {
                this["Admin_diffCustomNum2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Admin_colorYellow {
            get {
                return ((bool)(this["Admin_colorYellow"]));
            }
            set {
                this["Admin_colorYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_colorBlue {
            get {
                return ((bool)(this["Admin_colorBlue"]));
            }
            set {
                this["Admin_colorBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Admin_colorRed {
            get {
                return ((bool)(this["Admin_colorRed"]));
            }
            set {
                this["Admin_colorRed"] = value;
            }
        }
    }
}
